# -*- coding: utf-8 -*-
"""VAE,GAN,GCN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4hzgGyAu1iZQti1W9hvLZf2AB-jhkHw
"""

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

# Dimensions
input_dim = 20
latent_dim = 2

# Encoder
inputs = Input(shape=(input_dim,))
h = Dense(10, activation='relu')(inputs)
latent = Dense(latent_dim)(h)

# Decoder
h_decoded = Dense(10, activation='relu')(latent)
outputs = Dense(input_dim, activation='sigmoid')(h_decoded)

# Model
vae = Model(inputs, outputs)

# Compile
vae.compile(optimizer='adam', loss='mse')

# Dummy data
import numpy as np
x_train = np.random.rand(1000, input_dim)

# Train
vae.fit(x_train, x_train, epochs=10, batch_size=32)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Generator
generator = Sequential([
    Dense(16, activation='relu', input_dim=10),
    Dense(1, activation='sigmoid')
])

# Discriminator
discriminator = Sequential([
    Dense(16, activation='relu', input_dim=1),
    Dense(1, activation='sigmoid')
])

# Compile discriminator
discriminator.compile(optimizer='adam', loss='binary_crossentropy')

# GAN training loop (simple)
for epoch in range(1000):

    # Real data
    real_data = np.random.rand(32, 1)

    # Fake data
    noise = np.random.rand(32, 10)
    fake_data = generator.predict(noise, verbose=0)

    # Train discriminator
    discriminator.train_on_batch(real_data, np.ones((32, 1)))
    discriminator.train_on_batch(fake_data, np.zeros((32, 1)))

import torch
import torch.nn as nn

class SimpleGCN(nn.Module):
    def __init__(self):
        super(SimpleGCN, self).__init__()
        self.fc = nn.Linear(10, 2)

    def forward(self, x, adj):
        x = torch.matmul(adj, x)  # graph aggregation
        x = self.fc(x)
        return x

# Dummy data
x = torch.rand((5, 10))  # 5 nodes, 10 features
adj = torch.eye(5)       # adjacency matrix

# Model
model = SimpleGCN()

# Forward pass
output = model(x, adj)
print(output)